name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with: 
          cmd: scan
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test 
